# Generated by Django 5.2.7 on 2025-11-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'administrateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('num_cours', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=100)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
            options={
                'db_table': 'cours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id_disponibilite', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_disponibilite', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disponibilite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id_edt', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'emploi_du_temps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id_enseignant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'enseignant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnseignantMatiere',
            fields=[
                ('pk', models.CompositePrimaryKey('id_enseignant', 'id_matiere', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'enseignant_matiere',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipementSalle',
            fields=[
                ('id_equipement', models.AutoField(primary_key=True, serialize=False)),
                ('nom_equipement', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipement_salle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_matiere', models.CharField(max_length=20, unique=True)),
                ('nom_matiere', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'matiere',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('destinataire_type', models.CharField(max_length=20)),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('est_lue', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id_salle', models.AutoField(primary_key=True, serialize=False)),
                ('nom_salle', models.CharField(max_length=50, unique=True)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('type_salle', models.CharField(blank=True, max_length=50, null=True)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'salle',
                'managed': False,
            },
        ),
    ]
