# Generated by Django 6.0.2 on 2026-02-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrateur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disponibilite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emploidutemps',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enseignantmatiere',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipementsalle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salle',
            options={},
        ),
    ]
